# Change these first
owner: LRoffic # Your GitHub organization or username, where this repository lives
repo: LRipsum # The name of this repository

sites:
  - name: LRipsum
    url: https://lripsum.net
  - name: Oxalt
    url: https://oxalt.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: night
  # cname: lripsum.net
  baseUrl: /LRipsum
  name: LRoffic
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
